#! /bin/bash
source ../lib/clearLog.sh
source ../lib/createConfigLog.sh
source ../lib/collectLog.sh
#source ../lib/compareTwoFile.sh

clearLogs

# define category name
fileName=Burnin
mkdir ../log/$fileName

createConfigLog 0 $fileName

# test main

# =========

collectLog $fileName

#compareTwoFile "../log/configuration.log" "../log/$fileName/$fileName.log" "$fileName"

fileA=../log/configuration.log
fileB=../log/$fileName/$fileName.log
if diff "$fileA" "$fileB" -b -B >> ../log/$fileName/configuration_diff.log; then
    echo "Configuration Check => Passed" >> ../log/$fileName/summary.log
else
    echo "Configuration Check => Failed" >> ../log/$fileName/summary.log
fi