#! /bin/bash
source ../lib/clearLog.sh
source ../lib/createConfigLog.sh
source ../lib/collectLog.sh

clearLogs

# define category name
fileName=ConfigurationCheck
mkdir ../logs/$fileName

createConfigLog 0 $fileName
collectLog $fileName