#! /bin/bash
source ../lib/createConfigLog.sh
source ../lib/runBeforeTest.sh
source ../lib/collectLogs.sh

clearLogs

# define category name
fileName=ConfigurationCheck
mkdir ../logs/$fileName

collectLogs $fileName
config_build 0 ../logs/$fileName.log